apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-devslam-spring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: tanzu-devslam-spring
data:
  app.message: Hello Devslam!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: tanzu-devslam-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port:  "8080"
    spec:
      containers:
      - name: app
        image: ghcr.io/mosehsah/tanzu-devslam-spring:31
        resources:
          limits:
            memory: 1Gi
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
        env:
          # Read the ConfigMap mounted as a volume under /etc/config.
          - name: SPRING_CONFIG_IMPORT
            value: configtree:/etc/config/
        volumeMounts:
          - mountPath: /etc/config
            name: config
      volumes:
        - name: config
          configMap:
            name: config
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: tanzu-devslam-spring
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
