name: Build Image

on:
  push:
    branches: [ "feature/cicd" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: MoSehsah/tanzu-devslam-spring/demo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -DskipTests -Drevision=latest spring-boot:build-image --file demo-app/pom.xml

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: View Existing Images
      run: docker images
    - name: Tag Container Image
      run: docker tag docker.io/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
    - name: Push Container Image
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
